In [1]:
from module.screen import Screen
from module.movement import Rectangle
from module.network import Network
scr = Screen(20,20,2)

In [2]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [3]:
trace = [[0,0,1],[1,1,1],[2,2,1],[3,3,1]]
rec = Rectangle(trace, 2, 2)

In [4]:
network = Network(scr)
print(len(network.punit))
print(len(network.eunit))
print(network.punit[0].hex.pixels)
print(network.punit[0].hex.coord.xy)
print(network.punit[0].units)
print(network.punit[1].hex.pixels)
print(network.punit[1].hex.coord.xy)
print(network.punit[1].units)

25
25
[[2, 5], [2, 6], [2, 7], [3, 5], [3, 6], [3, 7], [4, 5], [4, 6], [4, 7], [5, 5], [5, 6], [5, 7]]
[[1.73205081]
 [3.        ]]
[(<module.unit.Unit object at 0x000001F47F3F51F0>, 1.0), (<module.unit.Unit object at 0x000001F47F3F56A0>, 1.0), (<module.unit.Unit object at 0x000001F47F3F5B50>, 1.0)]
[[6, 5], [6, 6], [6, 7], [7, 5], [7, 6], [7, 7], [8, 5], [8, 6], [8, 7]]
[[3.46410162]
 [3.        ]]
[(<module.unit.Unit object at 0x000001F47F3F5220>, 1.0), (<module.unit.Unit object at 0x000001F47F3F56D0>, 1.0), (<module.unit.Unit object at 0x000001F47F3F5B80>, 1.0)]


In [5]:
print(network.update([rec]))
print(network.update([rec]))
print(network.update([rec]))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.